config/routes.rb
Rails.application.routes.draw do

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :questions
  resources :answers, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :invites

  root to: 'static_pages#home'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/questionapprove', to: 'questions#add_approve', via: 'get'
  match '/questionshow', to: 'questions#show', via: 'get'
  match '/invitetest', to: 'invites#test', via: 'get'
  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/about'

end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers, dependent: :destroy
  has_many :qapproves
  belongs_to :user
  default_scope -> { order('created_at DESC') }
  validates :content, presence: true, length: { maximum: 1400 }
  validates :user_id, presence: true
  searchable do
   text :content, :title
  end
# Returns questions from the users being followed by the given user.
  def self.from_users_followed_by(user)
    followed_user_ids = "SELECT followed_id FROM relationships
WHERE follower_id = :user_id"
    where("user_id IN (#{followed_user_ids}) OR user_id = :user_id",
          user_id: user.id)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :signed_in_user, only: [:create, :destroy]
  before_action :correct_user, only: :destroy
  def index
    @query = Question.search do
      fulltext params[:search]
    end
    @questions = @query.results
    #redirect_to root_url
    render 'questions/_search'
  end
  def create
    @question = current_user.questions.build(question_params)
    if @question.save
      flash[:success] = "question created!"
      redirect_to root_url
    else
      render 'static_pages/home'
    end
  end
  def destroy
    Question.find(params[:id]).destroy
    redirect_to current_user
  end
  def show
    @question = Question.find(params[:id])
    $question_id = @question.id
    @answer = current_question.answers.build
    @answers = @question.answers
  end
  def add_approve
    @pre_approve=Qapprove.find_by(question_id:$question_id, user_id:current_user.id)
    if @pre_approve == nil
    @q_approve=Qapprove.new
    @q_approve.question_id = $question_id
    @q_approve.user_id = current_user.id
    @q_approve.save
    @question = Question.find($question_id)
    @approve_num = @question.approve + 1
    @question.update_attributes(approve:@approve_num)
      redirect_to current_question
    else
      @question = Question.find($question_id)
      @approve_num = @question.approve - 1
      @question.update_attributes(approve:@approve_num)
      @pre_approve.destroy
      redirect_to current_question
    end

  end

  private
  def question_params
    params.require(:question).permit(:title,:content)
  end
  def correct_user
    @question = current_user.questions.find_by(id: params[:id])
    redirect_to root_url if @question.nil?
  end
end

app/views/questions/_question.html.erb
<li>
  <span class="content"><%= link_to question.title, question %></span>
              <span class="timestamp">
              Posted at <%= question.created_at %>.
              </span>
  <% if current_user?(question.user)||current_user.admin %>
      <%= button_to "delete", question_path(question), :method => :delete ,style:"width:60px;margin-top:-18px;margin-left:250px;height:30px;float:left;" ,class: "btn btn-large btn-primary" %>
  <% end %>
  <br>
</li>

app/views/questions/_search.html.erb
<% if @questions.empty? %>
    <p>No questions found</p>
<% else %>
    <br>
    <ul>
      <% @questions.each do |question| %>
          <span class="content"><%= link_to question.title, question %></span>
              <span class="timestamp">
              Posted at <%= question.created_at %>. By <%= link_to question.user.name, question.user %>
              </span>

          <hr>
      <% end %>
    </ul>
<% end %>

app/views/questions/approve.html.erb
<h1>
        hehe
</h1>

app/views/questions/show.html.erb
<% provide(:title, "question") %>
<div class="row">

  <div class="span8">
        <h3><%= @question.title %></h3>
        <h5><%= @question.content %></h5>
  </div>
  <span class="timestamp">

    &nbsp&nbsp
    <%= link_to "approve", questionapprove_path, :method => :get%>(<%= @question.approve %>)
    &nbsp&nbsp
    <%= link_to "invite", invite_path%>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <span class="timestamp">Posted by <%= link_to @question.user.name, @question.user %> </span>
  </span>

  <div class="span8">

    <% if @question.answers.any? %>
        <br>
        <ol class="answers">
        <h4>answers (<%= @question.answers.count %>)</h4>

          <% @question.answers.each do |answer| %>
              <li>
                <span class="content"><%= answer.content %></span>
                <span class="timestamp">
                Posted at <%= answer.created_at %>.
                by <%= link_to answer.user.name, answer.user %>
                </span>
                <% if current_user?(answer.user)||current_user.admin %>
                    <%= button_to "delete", answer, :method => :delete,style:"width:60px;margin-top:-30px;margin-left:330px;height:30px;float:left;" ,class: "btn btn-large btn-primary"%>
                <% end %>

              </li>
          <% end %>
        </ol>
    <% end %>
  </div>
  <br>
  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/answer_form' %>
      </section>
    </aside>

  </div>
</div>