config/routes.rb
Rails.application.routes.draw do

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :questions
  resources :answers, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :invites

  root to: 'static_pages#home'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/questionapprove', to: 'questions#add_approve', via: 'get'
  match '/questionshow', to: 'questions#show', via: 'get'
  match '/invitetest', to: 'invites#test', via: 'get'
  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/about'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to "iQuest", root_path %>
    iQuest team
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse nav-stacked">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "iQuest", root_path, id: "logo" %>
      <nav>
        <ul class="nav nav-pills pull-right">
          <%= form_tag questions_path,:method => :get do %>
          <li><%= text_field_tag :search,params[:search],style:"width:200px;float:left;margin-right:10px;color:#49525c;height:40px;",placeholder: "search topics,questions..."%></li>
          <li><%= submit_tag "Search", :name => nil, :class => "button postfix" ,style:"width:100px;float:left;" ,class: "btn btn-large btn-primary" %></li>
           <% end %>
          <li><%= link_to "Home", root_path,style:"margin-left:10px;float:right;"%></li>
          
          <% if signed_in? %>
              <li><%= link_to "Users", users_path ,style:"float:right;"%></li>
              <li><%= link_to "Profile", current_user %></li>
              <% @invite_num=Invite.where(:invited_id => current_user.id, :read => false).count+Answermsg.where(:user_id =>current_user.id, :read => false).count %>
              <% if @invite_num!=0 %>
              <li style="position: relative;">
                <%= link_to "Message", invites_path ,style:"float:right;"%>
                <span style="display: block; position: absolute; right: 0px; top: 0px; background-color: #B00100;
                 color: #fff; border-radius: 50%; width: 20px; height: 20px; text-align: center;">
                  <%= @invite_num%>
                </span>
              </li>
                  <% else %>
                  <li style="position: relative;">
                    <%= link_to "Message", invites_path ,style:"float:right;"%>
                  </li>
                  <% end %>

              <li><%= link_to "Settings", edit_user_path(current_user) ,style:"10px;float:right;"%></li>
              <li>
                  <%= link_to "Sign out", signout_path, method: "get" ,style:"float:right;"%>
              </li>
          <% else %>
              <li><%= link_to "Sign in", signin_path ,style:"float:right;"%></li>
          <% end %>
           
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <%= stylesheet_link_tag "application", media: "all",
                          "data-turbolinks-track" => true %>

  <%= csrf_meta_tags %>
<%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <%= yield %>
  <%= render 'layouts/footer' %>
  <!-- JiaThis Button BEGIN -->
  <script type="text/javascript">
      var jiathis_config = {data_track_clickback:'true'};
  </script>
  <script type="text/javascript" src="http://v3.jiathis.com/code/jiathis_r.js?move=0&amp;uid=2041408" charset="utf-8"></script>
  <!-- JiaThis Button END -->
</div>
</body>
</html>